# Generated by Django 3.0.3 on 2020-02-18 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "mate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.Mate"
                    ),
                ),
            ],
        ),
    ]
