# Generated by Django 3.0.3 on 2020-02-19 20:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_assignment_week_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="key",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
