# Generated by Django 3.0.3 on 2020-02-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_notification_key"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="notification", unique_together={("email", "mate")},
        ),
    ]
