# Generated by Django 3.0.3 on 2020-03-02 00:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_auto_20200219_2123"),
    ]

    operations = [
        migrations.AddField(
            model_name="job", name="is_active", field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="NotificationSent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.Notification",
                    ),
                ),
            ],
        ),
    ]
