# Generated by Django 3.0.3 on 2020-03-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_auto_20200302_0021"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="notification", unique_together=set(),),
        migrations.RemoveField(model_name="notification", name="mate",),
    ]
