# Generated by Django 3.0.3 on 2020-05-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_todo"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
