# Generated by Django 3.0.3 on 2020-05-17 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_notification_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsent",
            name="notification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.Notification",
            ),
        ),
    ]
